config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  resources :surveys do
    member do
      get :survey_result
    end
  end
  resources :employees do
    resources :surveys, controller: 'survey_responses'
  end
  # resources :mood_responses, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "react_home#reactHome"
  get '/account' => 'pages#account', :as => :manager_root
  post 'surveys/:id/:employee_id/mood_responses/:question_id' => 'mood_responses#create', as: :surveys_mood_responses
  post 'surveys/:id/:employee_id/open_ended_responses' => 'open_ended_responses#create', as: :surveys_open_ended_responses
  post 'pages/send_emails'
  get 'survey_responses/success' => 'survey_responses#success', as: :survey_responses_success
  get '/nlp' => 'nlp_ruby_test#nlp_ruby_test'

  get 'test' => 'pages#test'


  namespace :api, defaults: { format:  :json } do
    namespace :v1 do
      resources :notes, only: [:index, :show, :create, :update, :destroy]
    end
  end

  # make all undefined path to get reactHome
  #get '*path', to: 'react_home#reactHome', via: :all

end

app/views/account_header/_header.html.erb
<style>
.nav {
    background: var(--gray);
    /* height: 80px; */
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1rem;
    position: sticky;
    top: 0;
    z-index: 10;
}
.navContainer {
    display: flex;
    justify-content: space-between;
    height: 80px;
    z-index: 1;
    width: 100%;
    padding: 0 24px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.logo {
    color: white;
    justify-self: flex-start;
    cursor: pointer;
    font-size: 30px;
    display: flex;
    align-items: center;
    margin-left: 24px;
    font-weight: bold;
    text-decoration: none;

    &:hover{
        color: var(--light);
    }
}

.menu {
    display: flex;
    align-items: center;
    list-style: none;
    text-align: center;
    margin-right: -22px;
}

.menuItem {
    color: white;
    display: flex;
    align-items: center;
    text-decoration: none;
    padding: 0 1rem;
    height: 100%;
    cursor: pointer;

    &:hover{
        color: var(--light);
    }
}

.btnContainer {
    display: flex;
    align-items: center;
    list-style: none;
}

/* .btn {
    border-radius: 50px;
    background: white;
    white-space: nowrap;
    color: black;
    padding: 10px 22px;
    font-size: 16px;
    outline: none;
    border: none;
    cursor: pointer;
    transition: all 0.2s ease-in-out;
    text-decoration: none;

    &:hover {
        transition: all 0.2s ease-in-out;
        background: var(--light);
    }
} */
</style>
<header>
    <nav class="nav">
        <div class="navContainer">
            <div class="logo">
                <%= link_to "Synergi", manager_root_path, style: "color: white;" %>
            </div>
            <div class="menu">
                <%= link_to "Employees", employees_path, class: "menuItem", style: "color: white; font-size: 24px;" %>
                <% # <%= link_to 'Notes', notes_path, class: "menuItem", style: "color: white; font-size: 24px;" %>
                <%= link_to "Surveys", surveys_path, class: "menuItem", style: "color: white; font-size: 24px;" %>
            </div>
            <div class="btnContainer">
                <% if manager_signed_in? %>
                    <%= link_to "Sign Out", destroy_manager_session_path, method: :delete, class: "btn btn-outline-light" %>
                <% else %>
                    <%= link_to "Sign in", new_manager_session_path, class: "btn" %>
                    <%= link_to "Sign up", new_manager_registration_path, class: "btn" %>
                <% end %>
            </div>
        </div>
    </nav>
</header>