config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  resources :surveys do
    member do
      get :survey_result
    end
  end
  resources :employees do
    resources :surveys, controller: 'survey_responses'
  end
  # resources :mood_responses, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "react_home#reactHome"
  get '/account' => 'pages#account', :as => :manager_root
  post 'surveys/:id/:employee_id/mood_responses/:question_id' => 'mood_responses#create', as: :surveys_mood_responses
  post 'surveys/:id/:employee_id/open_ended_responses' => 'open_ended_responses#create', as: :surveys_open_ended_responses
  post 'pages/send_emails'
  get 'survey_responses/success' => 'survey_responses#success', as: :survey_responses_success
  get '/nlp' => 'nlp_ruby_test#nlp_ruby_test'

  get 'test' => 'pages#test'


  namespace :api, defaults: { format:  :json } do
    namespace :v1 do
      resources :notes, only: [:index, :show, :create, :update, :destroy]
    end
  end

  # make all undefined path to get reactHome
  #get '*path', to: 'react_home#reactHome', via: :all

end

app/models/survey.rb
class Survey < ApplicationRecord
    flag :day_of_weeks, [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
    enum isAnonymous: [:anonymous, :identifiable]

    belongs_to :manager
    has_many :employee_surveys
    has_many :employees, through: :employee_surveys
    has_many :questions
    accepts_nested_attributes_for :questions, allow_destroy: true

    # def questions_attributes=(questions_attributes)
    #   questions_attributes.each do |i, questions_attributes|
    #     self.questions.build(questions_attributes)
    #   end
    # end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @survey = Survey.new
    @survey.questions.build
    @surveys = Survey.where(manager: current_manager)
    gon.Survey = Survey.all
    gon.Employee = Employee.all
    gon.questions = Question.all
    gon.MoodResponse = MoodResponse.all
    gon.OpenEndedResponse = OpenEndedResponse.all
    
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @survey.questions.build

    gon.Survey = Survey.all
    gon.questions = Question.all
    gon.current_manager = current_manager
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.manager = current_manager

    respond_to do |format|
      if @survey.save
        format.html { redirect_to '/surveys', notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to '/surveys', notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.questions.each do |q|
      q.destroy
    end
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to '/surveys', notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:name, :interval, :time_of_day, :isAnonymous, questions_attributes: [:id, :prompt, :question_type, :_destroy], day_of_weeks: [])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<style>
  .btn_new_survey_form {
    width: fit-content;
    border-radius: 50px;
    background: black;
    black-space: nowrap;
    color: black;
    padding: 6px 14px;
    margin-top: 5px;
    margin-bottom: 5px;
    font-size: 16px;
    outline: none;
    border: none;
    cursor: pointer;
    transition: all 0.2s ease-in-out;
    text-decoration: none;
    display: inline-block;

    &:hover {
      transition: all 0.2s ease-in-out;
      background: var(--light);
    }
  }
  .btn_right {
    margin-left: 20px;
  }
  .btn-create {
    margin-left: 39%;
  }

</style>

<%= include_gon(:init => true) %>
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div><b style="color: black;">Choose survey type:</b></div>
  
  <div>
    <%= link_to "Mood", { onclick: @a = 0 }, class: "btn btn-primary" %>
    <%= link_to "Open Ended", { onclick: @a = 1 }, class: "btn btn-info" %>
  </div>

  <% if params[:onclick].to_i == 1 %>
    <br/>
    <% # --------Open Ended---------- %>
    <div class="field">
      <b style="color: black;">Survey Name: </b><%= form.text_field :name %>
    </div>
    <br />

    <div class="field">
      <%= form.fields_for :questions do |q| %>
          <% render "surveys/question_fields", q: q %>
      <% end %>
      <%= link_to_add_fields("Add Question", form, :questions) %>
    </div>
    
    <br />

    <div class="field">
      <b style="color: black;">Remind employees every:</b><br />
      <span style="color: black;">
          <% # <%= form.collection_check_boxes :day_of_weeks, Survey.day_of_weeks.pairs %>
          <%= form.select :day_of_weeks, options_for_select(Survey.day_of_weeks.pairs), {}, { :multiple => true } %>
      </span><br />
      <br />
      <%= form.time_select :time_of_day, { ampm: true, minute_step: 5, default: Time.now } %>
    </div>
    
    <br />

    <div class="field">
      <b style="color: black;">Is this survey Identifiable or Anonymous?</b><br />
      <%= form.select :isAnonymous, options_for_select([["Identifiable", "identifiable"], ["Anonymous", "anonymous"]], "identifiable") %>
    </div>

    <br />
    
    <div class="btn_container">
      <%= form.submit "Create", class: "btn btn-primary btn-create" %>
    </div>
    <% # --------Open Ended end---------- %>
  <% else %>
    <div style="color: red; size: 10px;">*You are only allowed to have 1 mood survey.</div><br/>
    <div id="nomood">
      <% # ------Mood------- %>
      <div class="field">
        <b style="color: black;">Survey Name: </b><%= form.text_field :name %>
      </div>

      <br />

      <div class="field">
        <%= form.fields_for :questions do |q| %>
            <% render "surveys/mood_question", q: q %>
        <% end %>
      </div>

      <div class="field">
        <b style="color: black;">Remind employees every:</b><br />
        <span style="color: black;">
            <% # <%= form.collection_check_boxes :day_of_weeks, Survey.day_of_weeks.pairs %>
            <%= form.select :day_of_weeks, options_for_select(Survey.day_of_weeks.pairs), {}, { :multiple => true } %>
        </span><br />
        <br />
        <%= form.time_select :time_of_day, { ampm: true, minute_step: 5, default: Time.now } %>
      </div>
      
      <br />

      <div class="field">
        <b style="color: black;">Is this survey Identifiable or Anonymous?</b><br />
        <%= form.select :isAnonymous, options_for_select([["Identifiable", "identifiable"], ["Anonymous", "anonymous"]], "identifiable") %>
      </div>

      <br />
      
      <div class="btn_container">
        <%= form.submit "Create", class: "btn btn-primary btn-create" %>
      </div>
      <% # ------Mood end------- %>
    </div>
    
    
    <div style="color: black; size: 12px;" id="yesmood">
      You have already created a mood survey. <br/>
      Please create an open-ended survey instead.
    </div>

  <% end %>

<% end %>

<script>
    $('form').on('click', '.remove-fields', function(event) {
        $(this).prev('input[type=hidden]').val('1');
        $(this).closest('fieldset').hide();
        return event.preventDefault();
    });

    $('form').on('click', '.add_fields', function(event) {
        var regexp, time;
        time = new Date().getTime();
        regexp = new RegExp($(this).data('id'), 'g');
        $(this).before($(this).data('fields').replace(regexp, time));
        return event.preventDefault();
    });


    var hasMood = false;
    var Questions = gon.questions;
    var Surveys = gon.Survey;
    var current_manager = gon.current_manager;
    // console.log("Surveys: ", Surveys);
    var mood_surveys = [];
    var this_user_survey;
    var moodQuestions;
    // console.log("current manager: ", current_manager.id);
    this_user_survey = Surveys.filter(function(sy){
      return sy.manager_id == current_manager.id;
    });

    moodQuestions = Questions.filter(function(question){
      return question.question_type == 'mood';
    });
    // console.log("this user survey: ", this_user_survey);
    // console.log("mood questions: ", moodQuestions);
    
    for(var i = 0; i < moodQuestions.length; ++i){
      mood_surveys[i] = this_user_survey.filter(function(survey){
        return survey.id == moodQuestions[i].survey_id;
      });
      // console.log("mood survey: ", mood_surveys[i]);
      if(mood_surveys[i].length != 0){
        hasMood = true;
      }
    }
    // console.log("has mood survey? ", hasMood);
    if ( hasMood == false) {
      $("#nomood").show();
      $("#yesmood").hide();
    }
    else
    { //has mood survey already
      $("#nomood").hide();
      $("#yesmood").show();
    }

</script>

app/views/surveys/_mood_question.html.erb
<fieldset>
  <b style="color: black;">Question</b>
  <%= q.hidden_field :_destroy %>
  <%= link_to(" (Remove)", "#", class: "remove-fields") %>
  <br />
  <span style="color: black;">Prompt: </span><%= q.text_field :prompt %>
  <br />
  <br />
  <span style="color: black;">Type: </span><%= q.select :question_type, options_for_select([["Mood", "mood"]], "mood") %>
  <br />
  <br />
</fieldset> 

app/views/surveys/_question_fields.html.erb
<fieldset>
  <b style="color: black;">Question</b>
  <%= q.hidden_field :_destroy %>
  <%= link_to(" (Remove)", "#", class: "remove-fields") %>
  <br />
  <span style="color: black;">Prompt: </span><%= q.text_field :prompt %>
  <br />
  <br />
  <span style="color: black;">Type: </span><%= q.select :question_type, options_for_select([["Open-Ended", "open_ended"]], "open_ended") %>
  <br />
  <br />
</fieldset> 

app/views/surveys/edit.html.erb
<style>
body {
    background: white;
}
.container{
  display: flex;
  align-items: center;
  flex-direction: column;
  max-width: 400px;
  justify-content: center;
  margin-top: 8%;
}

h1, h2, h3, h4, h5, h6, p {
  color: black;
}

.note_nav {
    display: flex;
}
</style>

<%= render partial: "account_header/header" %>

<div class="container card bg-light mb-3">
    <br />
    <h1>Editing Survey</h1>
    <br />

    <%= render "form", survey: @survey %>

    <br />
    <div class="note_nav">
        <%= link_to "Cancel", surveys_path, class: "btn btn-secondary" %>
    </div>
    <br />
</div>

app/views/surveys/new.html.erb
<style>
body {
    background: white;
}
.container{
  display: flex;
  align-items: center;
  flex-direction: column;
  max-width: 400px;
  justify-content: center;
  margin-top: 8%;
}

h1, h2, h3, h4, h5, h6, p {
  color: black;
}
</style>

<%= render partial: "account_header/header" %>

<div class="container card bg-light mb-3">
    <br />
    <h1>New Survey</h1>
    <br />

    <%= render "form", survey: @survey %>

    <br />
    <%= link_to "Cancel", surveys_path, class: "btn btn-secondary" %>
    <br />
</div>

app/views/surveys/show.html.erb
<style>
body {
    background: white;
}
.container{
  display: flex;
  flex-direction: column;
  max-width: 400px;
  justify-content: center;
  margin-top: 8%;
}

h1, h2, h3, h4, h5, h6, p {
  color: white;
}

.date {
  align: left;
}

.show_nav {
    display: flex;
    margin-left: 36%
}
</style>

<%= render partial: "account_header/header" %>

<div class="container" style="text-align: center;">
  <p id="notice"><%= notice %></p>

  <tr>
      <strong style="color: white;"><td>Name: <%= @survey.name %></td></strong>
      <td><span style="color: white;">Notifications sent every <%= @survey.day_of_weeks %> @ <%= @survey.time_of_day.strftime("%I:%M %p") %></span></td>
      <td><span style="color: white;">Visibility: <%= @survey.isAnonymous.capitalize %></span></td>
      <td><span style="color: white;">Created on <%= @survey.created_at.strftime("%b %d") %> at <%= @survey.created_at.strftime("%I:%M %p") %> UTC</span></td>
      <td>
        <span style="color: white;">Questions:</span>
        <ol>
          <span style="color: white;"><% @survey.questions.each do |q| %></span>
            <li><span style="color: white;"><%= q.prompt %> (<%= q.question_type.dasherize.capitalize %>)</span></li>
          <% end %>
        </ol>
      </td>
    </td>

  <div class="show_nav">
    <%= link_to "Edit", edit_survey_path(@survey), style: "color: white; padding: 0 10px;" %>
    <p> | </p>
    <%= link_to "Back", surveys_path, style: "color: white; padding: 0 10px;" %>
  </div>
</div>